drop table users;
CREATE TABLE users (
  devtodevid int,
  lasttime text,
  pushavailable boolean,
  publisherid int,
  publisher text,
  campaign text,
  placement text,
  ad text,
  appversion text,
  appversionid int,
  cheater boolean,
  country text,
  created text,
  device text,
  deviceid int,
  firstappversion text,
  firstappversionid int,
  firstpaymentdate text,
  lastpaymentdate text,
  level int,
  locale text,
  osversion text,
  osversionid int,
  paymentcount int,
  paymentsum float,
  sdkversion text,
  sdkversionid int,
  segmentvalues text,
  tester boolean,
  mainid text,
  customuid text,
  idfa text,
  idfv text,
  advertisingid text,
  androidid text,
  username text,
  email text,
  phone text,
  photo text,
  age int,
  timezoneoffset int,
  gender int,
  ab text,
  testinggroup text
  );
  
COPY users(
  candidate_id,
  hire_reported,
  primary_keyword_candidate,
  candidates_city,
  candidates_country,
  experience_years,
  en_level_candidate,
  hire_salary,
  company_type
  ) FROM '/Users/Shared/test_jinni.csv'
DELIMITER ',' CSV HEADER;
